sample_rate: 24000

featex: # feature extraction module; components receive the output of torchaudio.load as input.
  spectrogram:
    cls: src.featex.spectrogram.SpecExtractor
    n_mels: 80
    n_fft: 2048
    win_length: 1200
    hop_length: 300

featproc: # feature processing module
  star_gan: # star-gan outputs spectrogram and target as a dict
    cls: src.featproc.star_gan.StarGAN
    init: checkpoints/stargan/Models/epoch_00150.pth
    config: checkpoints/stargan/Models/config.yml
    f0_ckpt: submodules/StarGANv2VC/Utils/JDC/bst.t7
    input:
      spectrogram: spectrogram
      source: source
      target: target
    n_targets: 20
  output: # what is passed to the next module
    featproc:
      - spectrogram
      - target
    featex: [] # non-processed features, from the featex config group

synthesis: # speech synthesis; receives featfusion's output as input
  cls: src.synthesis.parallel_wavegan.ParallelWaveGAN
  init: checkpoints/stargan/Vocoder/checkpoint-400000steps.pkl
  sample_rate: 24000
  input:
    spectrogram: spectrogram
